 #ifndef __SYMBOLS_H__
#define __SYMBOLS_H__
#define END				    0
#define INT				    1
#define BOOL			    2
#define VOID			    3
#define TRUE			    4
#define FALSE		        5
#define IF				    6
#define ELSE			    7
#define WHILE			    8
#define RETURN			    9
#define CIN				    10
#define COUT			    11
#define CONSTANT		    12
#define STRING_LITERAL	    13
#define LEFT_BRACE		    14
#define RIGHT_BRACE		    15
#define LEFT_PARANTHESIS    16
#define RIGHT_PARANTHESIS   17
#define LEFT_BRACKET	    18
#define RIGHT_BRACKET	    19
#define COMMA			    20
#define ASSIGN			    21
#define END_OF_INSTRUCTION  22
#define ADD				    23
#define SUBSTRACT		    24
#define MULT			    25
#define DIV				    26
#define NOT				    27
#define AND				    28
#define OR				    29
#define EQ				    30
#define NOT_EQ				31
#define LESS				32
#define GREATER				33
#define LESS_EQ				34
#define GREATER_EQ			35
#define LEFT_SHIFT			36
#define RIGHT_SHIFT			37
#define BAD_CHARACTER		38
#define IDENTIFIER			39
#endif